version: "3.5"
services:
  db:
    image: mysql:5.7
    container_name: mysql
    volumes:
      - db-data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=collective
      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass
    ports:
      - "3306:3306"

  backend:
    image: bcziraki/collectiveaccess:latest
    container_name: collectiveaccess
    environment:
      - DB_HOST=db
      - DB_NAME=collective
      - DB_ROOT_PASSWORD=rootpass
      - DB_USER=user
      - DB_PASSWORD=pass
      - DISPLAY_NAME=My Archive # optional
      - ADMIN_EMAIL=admin@my-archive.tld # optional
      - SMTP_SERVER=mail.my-archive.tld  # optional
    volumes:
        - backend-config:/var/www/providence/app/conf
        - backend-media:/var/www/providence/media/
        - frontend-config:/var/www/app/conf
    depends_on:
      - db
    ports:
      - "8081:80"

volumes:
  db-data:
  backend-config:
  backend-media:
  frontend-config:
